import { prisma } from "@/lib/prisma";
import { INTERNAL_PREFIX, SEQUENCE_LENGTH, ean13CheckDigit } from "@/lib/barcode";

/** Extracts the sequence portion (digits 3-12, 0-indexed 2..11) from a
 * barcode generated by this function, or null if it wasn't one of ours. */
function extractSequence(barcode: string | null): number | null {
  if (!barcode || !barcode.startsWith(INTERNAL_PREFIX) || barcode.length !== 13) return null;
  const seq = Number(barcode.slice(INTERNAL_PREFIX.length, INTERNAL_PREFIX.length + SEQUENCE_LENGTH));
  return Number.isFinite(seq) ? seq : null;
}

/**
 * One shared sequence pool per organization, spanning all three places a
 * barcode can live (CatalogItem.barcode, CatalogItemVariant.barcode,
 * CatalogItemPackaging.barcode) — otherwise two independently-numbered
 * pools could mint the same code for a product and one of its own
 * packagings. Same accepted-risk shape as `nextOrderNumber`
 * (src/actions/orders.ts): read the current max, +1, no transaction/retry
 * — the project's own precedent for per-org sequence numbers.
 *
 * Kept in a separate file from lib/barcode.ts specifically because this
 * function imports lib/prisma (Node-only) — see that file's own comment.
 */
export async function generateEan13(orgId: string): Promise<string> {
  const [item, variant, packaging] = await Promise.all([
    prisma.catalogItem.findFirst({
      where: { orgId, barcode: { startsWith: INTERNAL_PREFIX } },
      orderBy: { barcode: "desc" },
      select: { barcode: true },
    }),
    prisma.catalogItemVariant.findFirst({
      where: { catalogItem: { orgId }, barcode: { startsWith: INTERNAL_PREFIX } },
      orderBy: { barcode: "desc" },
      select: { barcode: true },
    }),
    prisma.catalogItemPackaging.findFirst({
      where: { catalogItem: { orgId }, barcode: { startsWith: INTERNAL_PREFIX } },
      orderBy: { barcode: "desc" },
      select: { barcode: true },
    }),
  ]);

  const maxSeq = Math.max(
    extractSequence(item?.barcode ?? null) ?? -1,
    extractSequence(variant?.barcode ?? null) ?? -1,
    extractSequence(packaging?.barcode ?? null) ?? -1,
  );
  const nextSeq = maxSeq + 1;

  const base12 = INTERNAL_PREFIX + String(nextSeq).padStart(SEQUENCE_LENGTH, "0");
  return base12 + ean13CheckDigit(base12);
}
