// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Only consumed by `prisma migrate diff --from-migrations` to generate
    // incremental migration SQL for prod (`migrate dev`'s own shadow-db step
    // has a separate, unrelated bug in this environment — see project memory
    // — which is why `db push` remains the dev-loop command, not this).
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
